name: idrone808
favicon: null
layout_spectrum: 0.89054
typography_spectrum: 0.68039
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8125
  lightness: 0.3508126998785883
  saturation: 0.3999384792987257
  rhythmicContrast: 0.07099467585794628
purpose: []
